[package]
name = "hooks-yew"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hooks = { version = "1.0.0-alpha.14", path = "../../../hooks/packages/hooks" }
yew = "0.19"
