[package]
name = "hooks-yew"
version = "1.0.0-alpha.1"
edition = "2021"
description = "Compile-time hook component for yew"
license = "MIT"
documentation = "https://docs.rs/hooks-yew"
repository = "https://github.com/frender-rs/hooks-yew"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
hooks-yew-derive = { version = "1.0.0-alpha.1", path = "../hooks-yew-derive" }

[dependencies.hooks]
version = "1.0.0-alpha.15"
default-features = false
features = ["derive"]
